{
  "_args": [
    [
      "promisepipe@^1.0.1",
      "/Users/vimalraj/Documents/Development/appium"
    ]
  ],
  "_from": "promisepipe@>=1.0.1 <2.0.0",
  "_id": "promisepipe@1.0.1",
  "_inCache": true,
  "_installable": true,
  "_location": "/promisepipe",
  "_npmUser": {
    "email": "esa-matti@suuronen.org",
    "name": "epeli"
  },
  "_npmVersion": "1.3.11",
  "_phantomChildren": {},
  "_requested": {
    "name": "promisepipe",
    "raw": "promisepipe@^1.0.1",
    "rawSpec": "^1.0.1",
    "scope": null,
    "spec": ">=1.0.1 <2.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "#DEV:/"
  ],
  "_resolved": "https://registry.npmjs.org/promisepipe/-/promisepipe-1.0.1.tgz",
  "_shasum": "7c5ccaecb399d9e3be8553fb91251c0a24e65921",
  "_shrinkwrap": null,
  "_spec": "promisepipe@^1.0.1",
  "_where": "/Users/vimalraj/Documents/Development/appium",
  "author": {
    "name": "Esa-Matti Suuronen"
  },
  "bugs": {
    "url": "https://github.com/epeli/node-promisepipe/issues"
  },
  "dependencies": {
    "q": "~0.9.7"
  },
  "description": "Pipe node.js streams safely with Promises",
  "devDependencies": {
    "mocha": "~1.13.0"
  },
  "directories": {},
  "dist": {
    "shasum": "7c5ccaecb399d9e3be8553fb91251c0a24e65921",
    "tarball": "http://registry.npmjs.org/promisepipe/-/promisepipe-1.0.1.tgz"
  },
  "homepage": "https://github.com/epeli/node-promisepipe#readme",
  "keywords": [
    "promise",
    "q",
    "stream"
  ],
  "license": "MIT",
  "main": "index.js",
  "maintainers": [
    {
      "name": "epeli",
      "email": "esa-matti@suuronen.org"
    }
  ],
  "name": "promisepipe",
  "optionalDependencies": {},
  "readme": "# promisePipe\n\nSafely pipe node.js streams while capturing all errors to a single promise.\n\n\n## API\n\n```\npromisePipe(<readable stream>, [transform streams...], <writeable stream>)\n```\n\nIt returns a promise. On success the resolved value will be an array of the\nstreams passed in. When rejected an error object is created with following\nkeys:\n\n  - `source`: The stream that caused the error\n  - `originalError`: Original error from the stream\n  - `message`: The error message from original error\n\n## Example\n\n```javascript\n\nvar promisePipe = require(\"promisepipe\");\n\npromisePipe(\n    fs.createReadStream(INPUT_FILE),\n    new UpcaseTransform(),\n    fs.createReadStream(OUTPUT_FILE),\n).then(function(streams){\n    console.log(\"Yay, all streams are now closed/ended/finished!\");\n}, function(err) {\n    console.log(\"This stream failed:\", err.source);\n    console.log(\"Original error was:\", err.originalError);\n});\n\n```\n\n## Install\n\n    npm instal promisepipe\n\n## Why?\n\nStream piping in node.js is cool, but error handling is not because streams\ndo not bubble to the target streams.\n\nFor example if the previous example is written like this:\n\n```javascript\nfs.createReadStream(INPUT_FILE)\n.pipe(new UpcaseTransform())\n.pipe(fs.createReadStream(OUTPUT_FILE))\n```\n\nIt might crash your program at any time. You must handle the errors\nfrom each stream manually like this:\n\n```javascript\nfs.createReadStream(INPUT_FILE).on(\"error\", function(err) {\n    // handle the error\n}).pipe(new UpcaseTransform()).on(\"error\", function(err) {\n    // handle the error\n}).pipe(fs.createReadStream(OUTPUT_FILE)).on(\"error\", function(err) {\n    // handle the error\n})\n```\n\nWhich is imo repeative and cumbersome (at least when you want to use promises).\n\n",
  "readmeFilename": "README.md",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/epeli/node-promisepipe.git"
  },
  "scripts": {
    "test": "mocha test.js"
  },
  "version": "1.0.1"
}
